# Generated by Django 3.1 on 2020-08-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='note',
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(default='Hello World', max_length=100, null=True),
        ),
    ]
